### PR TITLE
Update setup.md

### PR DESCRIPTION
**Pull request by vignesh1507**
Updated few typos in the .md file.

### CODE REVIEW

**Comment by g4ze** [comment]
hey vignesh! Thanks for the initiative! If all you wanted was to fix typos, i would suggest that you should go through other doc files as well and check them. That way we will be merging just one commit for all typos :)

**Comment by g4ze** [comment]
also can you please let me know if you're contributing via Hacktoberfest by GDG BU or not.

**Comment by vignesh1507** [comment]
Sure I'll check other docs also and yes I am contributing via hacktoberfest by GDG BU.

**Comment by g4ze** [comment]
We are not aiming to participate in the global hacktober fest. This is a local event conducted for BU students.

**Comment by g4ze** [comment]
You can fill the form and keep.updating it, provided in the hacktoberfest gdg-bu repo

**Comment by vignesh1507** [comment]
the form requires merged PR list, till now no PR of mine hasn't been merged yet by hacktoberfest gdg bu project's maintainers.

**Comment by g4ze** [comment]
You can still put it in the excel sheet and mark it as un merged.

**Comment by vignesh1507** [comment]
ok got it.

**Comment by vignesh1507** [comment]
Filled the form and as you said i have went through every documentation of this repo everything seems fine to me.

**Pull request merged**
